/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.threading.seq;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.math.BigInteger;

public class App {
    private static final Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        FactorialCalculator calculator = new FactorialCalculator();
        BigInteger factorial = calculator.calculateFactorial(100);
        logger.info("Factorial of 100 is " + factorial);
    }
}
